name: ci
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        neovim: [true, false]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - run: |
          echo "$(pwd)/vim-themis/bin/themis" >> $GITHUB_PATH
        id: themis

      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
          version: nightly

      - name: Run tests
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
          THEMIS_ARGS: ${{ (matrix.neovim && '-e -s --headless') || '-e -s' }}
          THEMIS_BIN: ${{ steps.themis.outputs.executable }}
        run: make _test
